import { Team } from "./types";

export const initialTeams: Team[] = [
  {
    id: "growth",
    name: "Growth Platform",
    description:
      "Squad responsavel por experimentos, onboarding e metricas do produto.",
    createdAt: "2026-02-12",
    role: "Administrador",
    projectsCount: 6,
    activeProjects: 4,
    completedProjects: 2,
    inProgressTasks: 31,
    delayedTasks: 4,
    completedTasks: 148,
    productivity: 87,
    isFavorite: true,
    admin: "Ana Costa",
    activities: [
      "Joao entrou na equipe.",
      "Maria concluiu a tarefa Revisar funil de ativacao.",
      "Pedro criou o projeto Experimentos Q3.",
      "Ana adicionou um novo membro.",
    ],
    members: [
      {
        id: "ana",
        name: "Ana Costa",
        fullName: "Ana Beatriz Costa",
        title: "Product Manager",
        email: "ana.costa@projectmanager.com",
        role: "Administrador",
        status: "Online",
        avatar: "AC",
        bio: "Coordena descoberta de produto, priorizacao e alinhamento com stakeholders.",
        joinedAt: "2026-02-12",
        projects: ["Experimentos Q3", "Portal do Cliente", "Onboarding 2.0"],
        assignedTasks: 18,
        completedTasks: 15,
        notes: [
          {
            id: "n1",
            content: "Prefere reunioes pela manha.",
            createdAt: "2026-06-03",
            updatedAt: "2026-06-03",
          },
        ],
      },
      {
        id: "joao",
        name: "Joao Lima",
        fullName: "Joao Henrique Lima",
        title: "Frontend Engineer",
        email: "joao.lima@projectmanager.com",
        role: "Membro",
        status: "Online",
        avatar: "JL",
        bio: "Especialista em React, acessibilidade e design systems.",
        joinedAt: "2026-03-04",
        projects: ["Portal do Cliente", "Design System"],
        assignedTasks: 24,
        completedTasks: 19,
        notes: [
          {
            id: "n2",
            content: "Especialista em React.",
            createdAt: "2026-06-08",
            updatedAt: "2026-06-12",
          },
        ],
      },
      {
        id: "maria",
        name: "Maria Santos",
        fullName: "Maria Eduarda Santos",
        title: "Data Analyst",
        email: "maria.santos@projectmanager.com",
        role: "Membro",
        status: "Ausente",
        avatar: "MS",
        bio: "Acompanha indicadores de aquisicao, retencao e receita.",
        joinedAt: "2026-03-18",
        projects: ["Metricas Growth", "Experimentos Q3"],
        assignedTasks: 16,
        completedTasks: 13,
        notes: [],
      },
      {
        id: "pedro",
        name: "Pedro Rocha",
        fullName: "Pedro Augusto Rocha",
        title: "Backend Engineer",
        email: "pedro.rocha@projectmanager.com",
        role: "Membro",
        status: "Offline",
        avatar: "PR",
        bio: "Cuida das APIs, integracoes e automacoes de dados.",
        joinedAt: "2026-04-02",
        projects: ["Experimentos Q3", "Automacao CRM"],
        assignedTasks: 21,
        completedTasks: 16,
        notes: [
          {
            id: "n3",
            content: "Responsavel pelo backend da Sprint 2.",
            createdAt: "2026-06-14",
            updatedAt: "2026-06-14",
          },
        ],
      },
    ],
  },
  {
    id: "mobile",
    name: "Mobile Experience",
    description: "Equipe focada na experiencia dos aplicativos iOS e Android.",
    createdAt: "2026-01-21",
    role: "Membro",
    projectsCount: 3,
    activeProjects: 2,
    completedProjects: 1,
    inProgressTasks: 19,
    delayedTasks: 2,
    completedTasks: 92,
    productivity: 79,
    isFavorite: false,
    admin: "Bruno Alves",
    activities: [
      "Bruno atualizou permissoes do projeto App Offline.",
      "Clara concluiu uma tarefa.",
      "Rafaela convidou um novo designer.",
    ],
    members: [
      {
        id: "bruno",
        name: "Bruno Alves",
        fullName: "Bruno Vinicius Alves",
        title: "Engineering Manager",
        email: "bruno.alves@projectmanager.com",
        role: "Administrador",
        status: "Online",
        avatar: "BA",
        bio: "Lidera o time mobile e remove bloqueios tecnicos.",
        joinedAt: "2026-01-21",
        projects: ["App Offline", "Push Center"],
        assignedTasks: 14,
        completedTasks: 12,
        notes: [],
      },
      {
        id: "clara",
        name: "Clara Nunes",
        fullName: "Clara Mariana Nunes",
        title: "Mobile Engineer",
        email: "clara.nunes@projectmanager.com",
        role: "Membro",
        status: "Ausente",
        avatar: "CN",
        bio: "Desenvolve fluxos nativos e melhora performance de telas criticas.",
        joinedAt: "2026-02-09",
        projects: ["App Offline", "Push Center"],
        assignedTasks: 20,
        completedTasks: 17,
        notes: [],
      },
      {
        id: "rafaela",
        name: "Rafaela Mendes",
        fullName: "Rafaela Cristina Mendes",
        title: "Product Designer",
        email: "rafaela.mendes@projectmanager.com",
        role: "Membro",
        status: "Offline",
        avatar: "RM",
        bio: "Pesquisa usuarios e cria prototipos para os fluxos mobile.",
        joinedAt: "2026-02-16",
        projects: ["Design Mobile", "Push Center"],
        assignedTasks: 12,
        completedTasks: 9,
        notes: [],
      },
    ],
  },
  {
    id: "ops",
    name: "Operations Core",
    description:
      "Organiza processos internos, documentacao e automacoes operacionais.",
    createdAt: "2025-11-08",
    role: "Administrador",
    projectsCount: 5,
    activeProjects: 3,
    completedProjects: 2,
    inProgressTasks: 27,
    delayedTasks: 6,
    completedTasks: 121,
    productivity: 74,
    isFavorite: false,
    admin: "Lucas Martins",
    activities: [
      "Lucas criou o projeto Base de Conhecimento.",
      "Nina removeu um membro inativo.",
      "Sofia concluiu uma tarefa atrasada.",
    ],
    members: [
      {
        id: "lucas",
        name: "Lucas Martins",
        fullName: "Lucas Ferreira Martins",
        title: "Operations Lead",
        email: "lucas.martins@projectmanager.com",
        role: "Administrador",
        status: "Online",
        avatar: "LM",
        bio: "Padroniza processos e acompanha SLAs dos fluxos internos.",
        joinedAt: "2025-11-08",
        projects: ["Base de Conhecimento", "Automacoes Internas"],
        assignedTasks: 22,
        completedTasks: 18,
        notes: [],
      },
      {
        id: "nina",
        name: "Nina Barros",
        fullName: "Nina Gabriela Barros",
        title: "QA Analyst",
        email: "nina.barros@projectmanager.com",
        role: "Membro",
        status: "Offline",
        avatar: "NB",
        bio: "Valida fluxos, regressao e criterios de aceite.",
        joinedAt: "2025-12-01",
        projects: ["Qualidade Continua"],
        assignedTasks: 17,
        completedTasks: 11,
        notes: [],
      },
      {
        id: "sofia",
        name: "Sofia Ribeiro",
        fullName: "Sofia Helena Ribeiro",
        title: "Technical Writer",
        email: "sofia.ribeiro@projectmanager.com",
        role: "Membro",
        status: "Online",
        avatar: "SR",
        bio: "Documenta processos, releases e manuais internos.",
        joinedAt: "2026-01-03",
        projects: ["Base de Conhecimento", "Portal Interno"],
        assignedTasks: 15,
        completedTasks: 14,
        notes: [],
      },
    ],
  },
];
